substitutions:
  _REGION:        "default-region"
  _AR_REPO:       "default-repo"
  _IMAGE_NAME:    "default-image"
  _JOB_NAMES:     "default-job-1 default-job-2"

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest'
      - '-f'
      - 'docker/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-sha'
    waitFor: ['build-docker-image']
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-latest'
    waitFor: ['build-docker-image']
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'deploy-jobs'
    waitFor: ['push-image-sha']
    entrypoint: bash
    args:
      - -c
      - |
        if [ -n "${_JOB_NAMES}" ]; then
          for job in ${_JOB_NAMES}; do
            echo "Deploying/Updating Job: $job"
            gcloud run jobs deploy $job \
              --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA \
              --region=${_REGION} \
              --quiet
          done
        else
          echo "No jobs to deploy."
        fi

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest'

timeout: '1200s'